import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Header from '@/components/navigation/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ztNature = localFont({
  src: [
    {
      path: './fonts/ztnature/ZTNature-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-zt-nature',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={ztNature.variable}>
      <head>
      </head>
      <body
        className={'antialiased'}
      > 
        <div className={`bg-black ${ztNature.variable} text-white pb-4`}>
          <Header/>
          {children}
        </div>
      </body>
    </html>
  );
}
