import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Header from '@/components/navigation/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceMono = localFont({
  src: [
    {
      path: './fonts/space-mono-regular.ttf',
      weight: '400',
      style: 'normal',
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={spaceMono.className}>
      <head>
      </head>
      <body
        className={'antialiased'}
      > 
        <div className={`min-h-screen w-full bg-black text-white pb-4 text-sm md:text-md`}>
          <Header/>
          {children}
        </div>
      </body>
    </html>
  );
}
